FROM windows:10iot_enterprise_ltsc2021 as stage00

# Install chocolatey
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

# do a reboot (each RUN is a full boot -> execute -> shutdown) cycle.

# install software
RUN choco install -y visualstudio2022community --execution-timeout=50000
RUN choco install -y visualstudio2022-workload-nativedesktop --execution-timeout=50000
RUN choco install -y git --execution-timeout=50000
RUN choco install -y flutter --execution-timeout=50000

# reduce image size

RUN ..disk-optimize

# Prepare final image

FROM scratch
COPY --from=stage00 / /

ENV QEMU_KVM_FLAGS=""
ENV QEMU_RAM_LIMIT=4G
ENV FORWARD_PORTS="8080"

ENTRYPOINT [ "/entrypoint.sh" ]
SHELL [ "/entrypoint.sh" ]

RUN sleep 300
